### ISSUE TITLE
Best python install for Mac OS X?

### ISSUE THREAD

**Issue by earnric** [prickly-pythons/prickly-pythons#16]
So I just got a new desktop MacPro ... I use the Enthought distribution on my laptop, but thought there might be a better on to 'install from scratch' on a new Mac system.

Thoughts?

**Comment by earnric** [comment]
Sounds like Anaconda is the way to go?

**Comment by piyanatk** [comment]
If you prefer to manage packages and create virtual environment from the command-line, I recommend Anaconda. Enthought package management GUI works better than their command-line counterpart. Internally, both distribution (and any distribution) are all the same.

**Comment by earnric** [comment]
Ok cool... Just installed Anaconda 3 on my MacPro ... we'll see if I can run all my old 2.7 programs!

Thx
