### ISSUE TITLE
Meetings on hold?

### ISSUE THREAD

**Issue by kpolsen** [prickly-pythons/prickly-pythons#19]
@prickly-pythons/users : It's been over a month and there hasn't been any requests for new topics, so either people don't have time for python meetings or have reached a place where they learn better on their own. 
Conclusion: **I'm considering putting our meetings on hold** for the time being! Meaning, no meeting this upcoming Monday. We can start up later this semester if I hear demands to do so.

Please leave a comment here if you absolutely don't think we should put the meetings on hold.

**Comment by godber** [comment]
Sorry I haven't really had time to contribute this semester.  I've definitely been too busy.
