### ISSUE TITLE
How to move the landing page to sees-python-users.github.io?

### ISSUE THREAD

**Issue by piyanatk** [prickly-pythons/prickly-pythons#3]
@godber How did you do it for DesertPy? Any suggestion is welcome

**Comment by godber** [comment]
For desertpy, I setup a github pages page using this information: https://help.github.com/categories/github-pages-basics/

I used a custom domain, which I already owned, and generated the static site with pelican.  The URL shown here: https://github.com/sese-python-users can be changed in settings.

I am not quite sure I understand your question exactly.

**Comment by piyanatk** [comment]
Landing page fixed. I made a new repo [sese-python-users.github.io](https://github.com/sese-python-users/sese-python-users.github.io) (only admin access for now), and the auto-generated page seems to have the desired url http://sese-python-users.github.io.
