### ISSUE TITLE
Adding tutorials to the repo

### ISSUE THREAD

**Issue by piyanatk** [prickly-pythons/prickly-pythons#5]
We should link online tutorials such as the Software Carpentry tutorials to the tutorial directory in the repo. I am not sure how you link another github repo to a sub-directory in the repo, or if there is a better way. Anyone has a thought on this?

**Comment by piyanatk** [comment]
@abhijithrajan I saw you try to push a directory. It might be better to link external repo as a submodule.

**Comment by abhijithrajan** [comment]
That's what I realized and decided to remove it.

**Comment by piyanatk** [comment]
@abhijithrajan @spacegal-spiff I linked Jake VDP python class to the tutorials directory with submodule. Very easy. Can you link software carpentry GitHub? We might need to put a link to the actual readable website/ipython notebooks of those tutorials somewhere too. Maybe on the main group website? Or a "RESOURCE.md" file on the main repository?

**Comment by piyanatk** [comment]
how to use submodule https://git-scm.com/book/en/v2/Git-Tools-Submodules
