### ISSUE TITLE
Agenda for Sep 24

### ISSUE THREAD

**Issue by piyanatk** [prickly-pythons/prickly-pythons#8]
Can everyone reply with anything that they would like to discuss this week please?

**Comment by piyanatk** [comment]
- Installing Python
- Introduce GitHub platform
- Survey of Interest
- Help on the platform

**Comment by amloren1** [comment]
It would depend on everyone's level if experience I think. Maybe attempt to
get everyone on a similar level this week.

**Comment by piyanatk** [comment]
@amloren1 That would be impossible to do, but the point of this GitHub platform is exactly to provide people with lover-level a place to ask questions from people with higher-level. If you want to learn any specific topic, you should post it here, and I am sure someone will be able to help you.

**Comment by piyanatk** [comment]
@kpolsen Can you take a note of this meeting as a *.md file and upload it `/meeting`?
